openapi: 3.0.0
info:
  title: kotoba-api
  version: "1.0"
  description: API serving the Japanese language learning app Kotoba
  license:
    name: MIT
  contact:
    name: Anita Kowalska
    url: "https://github.com/anitakniaziew"
servers:
  - url: "https://europe-west2-kotoba-c36b8.cloudfunctions.net/kotoba"
    description: Production
tags:
  - name: learning
    description: Endpoints used for learning
  - name: admin
    description: Endpoints for content management
paths:
  /phrasesToLearn:
    get:
      summary: Fetch Phrases to Learn
      tags:
        - learning
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      description: A single phrase
                      properties:
                        PL:
                          type: string
                          description: Polish translation
                        JP:
                          type: string
                          description: Japanese translation
                      required:
                        - PL
                        - JP
                  meta:
                    type: object
                    required:
                      - total
                    description: Metadata describing the collection
                    properties:
                      total:
                        type: integer
                        minimum: 0
                        description: Number of total words to learn
                required:
                  - data
                  - meta
              examples: {}
      operationId: get-phrases
      description: Returns the next phrases to learn based on the learning optimization algorithm.
    parameters: []
  /phrasesCount:
    get:
      summary: Fetch Phrases Count
      tags:
        - learning
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: An object containing phrase counts
                    properties:
                      phrasesBeingLearned:
                        type: integer
                        minimum: 0
                        description: The number of phrases being learned
                      phrasesToReview:
                        type: integer
                        minimum: 0
                        description: The number of phrases to review now
                      phrasesToLearn:
                        type: integer
                        minimum: 0
                        description: The number of phrases yet to learn
                    required:
                      - phrasesToReview
                required:
                  - data
              examples: {}
      operationId: get-phrases-count
      description: Returns various counts of phrases - the ones to learn, the ones to review, etc.
    parameters: []
  /phrases:
    post:
      summary: Add phrases to database
      tags:
        - admin
      responses:
        "201":
          description: Created
      operationId: post-phrases
      description: Registers new phrases in the database.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  minItems: 1
                  description: List of phrase objects
                  items:
                    type: object
                    properties:
                      PL:
                        type: string
                      JP:
                        type: string
                    required:
                      - PL
                      - JP
              required:
                - data
  /answers:
    post:
      summary: Send answers
      tags:
        - learning
      responses:
        "202":
          description: Accepted
      operationId: post-answers
      description: Allows to send a batch of answers for statistical purposes and calculating learning intervals.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      question:
                        type: string
                        description: The phrase in question
                      answer:
                        type: string
                        description: User answer
                      language:
                        type: string
                        description: Language of the phrase in question
                        enum:
                          - PL
                          - JP
                    required:
                      - question
                      - answer
components:
  schemas: {}
  securitySchemes: {}
